### ISSUE TITLE
Support Forge tag format on Fabric

### ISSUE THREAD

**Issue by Fuzss** [Apollounknowndev/inverted-tag-entries#1]
Love the mod, great to be able to remove values from tags on Fabric.

Forge / NeoForge natively offer this functionality, but with a different format. Would be great if you could support that, would make using this much easier for multiloader projects so there is no need for separate data files.

Forge leaves the `values` block as is, and adds an additional `remove` block that functions exactly the same as `values`, but for removals. Example:
https://github.com/Fuzss/universalenchants/blob/main/1.20.4/Common/src/generated/resources/data/minecraft/tags/enchantment/incompatible/smite.json

**Comment by Fuzss** [comment]
Ah, just saw your mod is for Forge, too. From quickly glancing at your code not sure if Forge's new `remove` field is properly repsected?

**Comment by Apollounknowndev** [comment]
Added in v1.1.0.
